name: tradline
description: online trading platform 


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ui related pub
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1

  # state management
  bloc: ^6.1.0
  flutter_bloc: ^6.1.1

  # network related pub
  dio: ^3.0.10

  # database related pub
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.24

  # model related pub
  built_value: ^7.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  rxdart: ^0.24.1
  build_runner: any
  built_value_generator: ^7.1.0
  bezier_chart: ^1.0.16

flutter:
  uses-material-design: true
